/// Flutter icons ToDog
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToDog
///      fonts:
///       - asset: fonts/ToDog.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ToDogFont {
  ToDogFont._();

  static const _kFontFam = 'ToDogFont';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData donelist =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData footprint =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData notdonelist_1 =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData dog_out = const IconData(0xe808, fontFamily: _kFontFam);
}
